cmd/add.go, cmd/delete.go, cmd/notifications.go, cmd/update.go, lagoon/projects/notifications.go, output/main.go
This PR adds or updates the following commands. Adding, removing and updating slack or rocketchat notifications is now possible. Listing notifications by project, or all projects is also possible
```
add slack
add project-slack
add rocketchat
add project-rocketchat
delete slack
delete project-slack
delete rocketchat
delete project-rocketchat
update slack
update rocketchat
list slack
list rocketchat
```
closes #3
=> Add slack and rocketchat notification commands

api/types.go, cmd/list.go, cmd/root.go, cmd/run.go, cmd/tasks.go, lagoon/environments/tasks.go, lagoon/environments/tasks_test.go
This PR adds the commands to be able to run and list tasks
```
$ lagoon list tasks -p high-cotton -e master
ID	REMOTEID	NAME              	STATUS   	CREATED            	STARTED            	COMPLETED          	SERVICE 
29	-       	Drush_archive-dump	failed   	2019-11-10 22:04:41	-                  	-                  	-      	
28	-       	Drush_archive-dump	failed   	2019-11-10 21:43:38	-                  	-                  	-      	
6 	-       	Drupal_Archive    	failed   	2018-10-07 23:02:41	2018-10-07 23:03:41	2018-10-07 23:05:41	-      	
7 	-       	Site_Status       	active   	2018-10-07 23:02:41	2018-10-07 23:03:41	-                  	-      	
8 	-       	Drupal_Archive    	succeeded	2018-10-07 23:02:41	2018-10-07 23:03:41	2018-10-07 23:13:41	-
```
```
$ lagoon run drush-archivedump …
```
=> Add commands to run and list tasks

README.md
A homebrew tap was created for lagoon-cli, this PR changes the MacOS instructions to prefer that installation method.
Closes #22
=> #22 - add homebrew installation

cmd/config.go, cmd/project.go, cmd/root.go, cmd/shared.go, cmd/web.go, docs/commands/lagoon.md, docs/commands/lagoon_config_add.md, docs/commands/lagoon_config_delete.md, docs/commands/lagoon_kibana.md
With #40 and #41 there were missing config flags for non-default amazeeio lagoon configurations, this adds them in.
Improvement - Add additional flags for configuring non default amazeeio lagoon instances
=> Add non-existing config flags for ui and kibana urls

cmd/login.go
Try to use the SSH agent before attempting to open any SSH key files.
This offloads complex key handling, multiple key formats etc.
Improvement - Prefer SSH agent over keyfile parsing.
Closes #43
=> Attempt to use the SSH agent before looking for key files

cmd/config.go, cmd/deploy.go, cmd/environment.go, cmd/project.go, cmd/root.go, cmd/variables.go
This copies some of the changes from @shreddedbacon's old import/export branch to add a message to the yes/no prompt.
This is in support of the import/export PR.
Improvement - Add message to prompts
n/a
=> Add message to yesNo prompt

cmd/login.go
The new line in the `sshHost` broke on darwin
```
Unable to refresh token, you may need to run `lagoon login` first, error was couldn't connect to ssh.lagoon.amazeeio.cloud:32222
: dial tcp: lookup tcp/32222
: nodename nor servname provided, or not known
```
Removing fixes it, @smlx can you verify if the new line is required on linux?
=> new line breaks ssh dial on darwin

cmd/config.go, cmd/root.go, docs/commands/lagoon_config_feature.md
To be able to disable local checkout out git repository and branches, there should be a flag to enable or disable this functionality
```
lagoon config feature --disable-project-directory-check true
```
Feature - Flag to disable local directory check for a lagoon project
closes #102
=> Disable directory check

cmd/users.go, docs/commands/lagoon_add_user-sshkey.md, internal/helpers/helpers.go
Fix for newline characters when specifying a key with no comment.
Also implemented a flag to specify a key value directly as a flag. And set default behaviour to name the key the same as the user email address if a name is not defined (lagoon will complain if it is already used though)
Bugfix - Trim new lines from the end of SSH keys
Improvement - Allow key to be added without specifying a file
closes #111
=> Improvements to adding SSH keys

cmd/root.go, go.sum, internal/helpers/helpers.go
Setting the envvar `LAGOONCONTEXT` to the name of the cluster to use to allow for overrides of the `default` value in the main lagoon config file for the cli.
```
export LAGOONCONTEXT=mycluster
```
Now any `lagoon x` commands will try to execute against `mycluster` instead of whichever may be defined in `default:` in the main `~/.lagoon.yml` file.
Improvement - New config related environment variable for defining cluster to use.
=> Environment variable to define the Lagoon cluster to use

cmd/notificationsrocketchat.go, cmd/notificationsslack.go
This PR fixes the `lagoon delete slack` and `lagoon delete rocketchat` commands due to the lack of `-n` flag
Since this PR is not possible to delete a slack or rocketchat notification
Bugfix - Fix slack/rocketchat notification deletion  (#130)
closes #130
=> Fix lagoon delete slack/rocketchat notification

Dockerfile
Adding a Dockerfile to the repo so dockerhub can build out an image to use lagoon CLI via docker.
Tested build via `8thom/lagoon-cli`
Example: `docker run -ti -v $HOME:/root 8thom/lagoon-cli list projects`
*Requires your home directory to be mounted for access to the SSH keys and `~/.lagoon.yml` config.
=> Added Dockerfile to build lagoon-cli image.

builds/release_template.md
When first downloaded into a user's PATH, the binary is not executable. This PR just adds a `chmod` command to the instructions in the release template.
Documentation - Update binary installation instructions to include setting executable permissions on the downloaded file (#157)
closes #157
=> Add 'chmod' command to release template for OSX/Linux binary instructions

cmd/get.go, cmd/list.go, cmd/notificationsrocketchat.go, cmd/notificationsslack.go, cmd/shared.go, cmd/users.go, pkg/api/backups.go, pkg/api/environments.go, pkg/api/groups.go, pkg/api/projects.go, pkg/api/tasks.go, pkg/api/users.go
=> Better message when no data returned

cmd/groups.go, cmd/users.go
In Lagoon, user account email addresses automatically get transformed into lowercase. Either by Keycloak, or somewhere in the API. This forces email addresses entered by users to be lowercase when being sent to the Lagoon API.
An extra issue needs to be raised against Lagoon to do this in the API itself.
Closes #168
=> Transform email addresses to lowercase

cmd/config.go
Quick fix to add the default amazeeio port 32222 to default configuration generation
=> Add the default port to config generation

cmd/config.go, cmd/login.go, cmd/root.go, cmd/ssh.go, cmd/web.go
After PR #179 was merged, it uncovered a slight problem where if the `--lagoon $lagoon` flag was not defined, the CLI got confused and was unable to determine which lagoon from the config file to target.
This PR makes sure that the `current` lagoon is set in the correct location and updates commands to use the correct current value.
closes #182
=> make sure the cli correctly knows which lagoon to use

docs/index.md
Adds the installation method to https://amazeeio.github.io/lagoon-cli/
=> Add installation method to show on the docs site

pkg/lagoon/environments/tasks.go
This fixes a hardcoded magic number in the lagoon invokable task runner
=> Fixes thinko magic number hardcoded into task runner

.github/workflows/mkdocs.yaml, .github/workflows/release.yaml
This will trigger a docs rebuild on tag pushes.  We can also create a "docs" branch if we need to update the docs between releases.
=> setup mkdocs workflow for github actions

.github/workflows/goreleaser.yaml, .github/workflows/lagoon-cli.yaml, .goreleaser.yml, Makefile
This PR configures goreleaser for use with this repo.
It will:
* Add a Homebrew release at uselagoon/lagoon-CLI (Linux/macOS + amd64/arm64 compatible)
* Publish the binaries and tar.gz to a GitHub release, with a checksum file
* Add a changelog
* Format the release note (sample in a comment below)
* Also work in a forked repo - the releases, brew etc will push to the fork in the event of a tag - so you can self-publish pre-releases etc safely
I've added an extra secret GH_ACTION_PAT that will need refreshing
I've disabled the `releaser` action, for now, we can remove it later
=> add goreleaser action

cmd/project.go, pkg/api/types.go, pkg/lagoon/projects/main.go
closes #222 
Can now also update FactsUI bool
```
> go run main.go -l amazeeio update project -p example-drupalcon-portland-2022 -j "{ \"factsUi\": 1 }"
Result: success
Project Name: example-drupalcon-portland-2022
```
=> Allowing json string flag to be used when updating a project

cmd/config.go, cmd/login.go, cmd/root.go, cmd/shared.go, cmd/ssh.go, cmd/ssh_test.go, docs/commands/lagoon_config_list.md, go.mod, go.sum, internal/lagoon/config.go, pkg/lagoon/ssh/main.go
This adds some additional features to the config file for supporting specific SSH keys per configured cluster.
It also adds support for showing the key identity information in the `--conn-string` output of the SSH command (#198).
The additional configuration change to add SSH keys will allow users to create configurations, each with a dedicated private key if they choose. 
Using this method, you can use the `--lagoon` flag, or the `LAGOON_CONTEXT` environment variable to choose which cluster configuration to use, and the key defined will be used for token generation, and also SSH access without having to define the `--ssh-key/-i` flag.
An example would be if a user has 2 unique users on a single Lagoon instance that can both access different projects, you could create two dedicated …
=> Feat: Support for SSH key definition in configuration file

cmd/helpers.go, cmd/helpers_test.go, cmd/ssh.go
The current implementation of ssh requires the user to use the version of the environment name that is dns compliant as this is how SSH in Lagoon works, like `feature-branch`. All other commands in Lagoon require the environment name as it is used, like `feature/branch`.
This PR brings support for the format of environment name that all other commands in the CLI use. Using the `feature-branch` style environment name is still supported too.
closes #147
=> feat: support lagoon environment name in ssh

.github/workflows/lagoon-cli.yaml, .github/workflows/mkdocs.yaml
Just some updates to which actions run when. Pushing to gh-pages for documentation updates should only be done when a tag is released.
Tests should run when any code is merged to main
=> chore: only push to gh-pages on tags

docs/config.md
The existing documentation states that you can change the default lagoon and provides an example of such:
```
lagoon config default amazeeio
```
Attempting to enact a change to the default lagoon by following the documentation results in a failure with the message:
```
Not enough arguments
Set the default Lagoon to use
```
It is actually required that we add another flag in order for the command to execute successfully, that being the --lagoon flag as follows:
```
lagoon config default --lagoon amazeeio
```
With the flag set, it will now complete the change and report success which can be confirmed by listing your default lagoon.
@AlannaBurke tagged as per contribution guidelines.
Put …
=> Update to change default lagoon command documentation

pkg/api/types.go, pkg/lagoon/environments/main.go, pkg/lagoon/environments/main_test.go
Follow up from #259. Missed a field on the `Environment` struct. Also it was discussed that we can fully remove this since it's not used (and it's been broken for a couple years) and we don't have a BC break policy that would prevent it.
n/a
=> change: Remove deprecated MonitoringURLs

cmd/project.go, internal/schema/project.go
Lagoon v2.12.0 contains a change in the response field for metadata. A mariadb update resulted in the data that was previously returned as an escaped string now returns as valid json.
The Lagoon CLI used to process this field as a string, now it returns as a map and processed using JSON utils.
Fix - Handle metadata properly
closes #266
=> fix: update metadata to use map for json response

cmd/ssh.go, pkg/lagoon/ssh/main.go
Fixes an issue where if a shell command exits, it could ruin a users terminal.
closes #269
=> fix: handle ssh errors to reduce terminal breaking

cmd/ssh.go
Fix if the ssh command exits to actually exit with 1
closes #277
=> fix: add exit for ssh commands that exit

cmd/ssh.go, cmd/ssh_test.go
Enables ssh-portal support by default, falls back to legacy if not found
=> refactor: enable ssh-portal support by default

cmd/list.go, pkg/output/main.go
When running `list variables` on a project/environment where none exist an error is returned alongside the cli `Usage` text. Rather than returning an error, this updates the cmd to output the message via `Stderr` with an empty table (similar functionality to how the api currently operates) and doesn't unnecessarily display the `Usage` text. Also updates the `output` package to handle the error strings.
=>  Change: Updates the output from an `Error` to `Stderr` when listing variables where none are set

cmd/list.go
Because the value is the last column, don't replace the returned value with `-` if the value in the API is actually empty
=> fix: if value of variable is empty, dont replace it with -

cmd/notificationsemail.go, docs/commands/lagoon_delete_notification.md, docs/commands/lagoon_delete_notification_email.md
Previously the delete email notification command was unusable because of a copy/pasta error from the delete webhook notifiction
```
tobybellwood@pop-os:~$ lagoon delete notification email -n example-email
Error: unknown shorthand flag: 'n' in -n
Usage:
lagoon delete notification [command]
Aliases:
notification, n
Available Commands:
microsoftteams         Delete a Microsoft Teams notification from Lagoon
project-email          Delete a email notification from a project
project-microsoftteams Delete a Microsoft Teams notification from a project
project-rocketchat     Delete a RocketChat notification from a project
project-slack          Delete a Slack notification from a project
project-webhook        Delete a webhook notification from a project
rocketchat             Delete a RocketChat …
```
=> fix: update delete email notification

pkg/api/types.go, pkg/lagoon/projects/main.go
The API has supported exposing the publicKey on its own field rather than requiring users to decode the privateKey. This updates the CLI to use this new field where possible, and only request the privateKey if reveal is requested (to respect permissions in the api)
=> refactor: use publicKey field to avoid permission errors on privateKey

cmd/deploy.go
It seems as thought the `--returnData` flag was almost completely implemented for `deploy pullrequest` - it just wasn't being passed through as part of the payload to the Lagoon library. This small fix patches that.
=> fix: Adds ReturnData to pull request deploy

cmd/deploy.go, cmd/helpers.go, cmd/helpers_test.go, go.mod, go.sum, internal/lagoon/client/_lgraphql/deployEnvironmentBranch.graphql, internal/schema/deploy.go, internal/schema/envVar.go
This POC introduces the ability to pass build variables to a deployment in a way that mirrors the GraphQL API.
It adds the ability to add command line arguments of the form `--buildvar KEY1=VAL1 [--buildvar KEY2=VAL2]` etc.
These will then be passed along to the graphQL deploy call as build variables.
This functionality is particularly important when deploying a new environment that requires build variables, which cannot be set since the environment doesn't yet exist.
=> Feature: Adds build variables to deployBranchCmd

Makefile, cmd/raw.go, cmd/root.go, docs/commands/lagoon.md, docs/commands/lagoon_raw.md, mkdocs.yml
This adds support for the `raw` command which allows users to pass raw graphql commands to the API. The output is raw JSON like the API would respond with, this way tools like `jq` can be used on the output.
Example to list all projects.
```
lagoon raw --raw 'query allProjects{ allProjects { name } }' | jq
```
=> feat: add raw query command functionality

cmd/deploy.go, cmd/helpers_test.go
The `StringSlice` type has some checks that splits with comma separated values, `StringArray` doesn't appear to do the same thing. This updates the commands to use the `StringArray` type.
closes #333
=> fix: use stringarray instead of stringslice for buildvars

cmd/groups.go, cmd/shared.go
Fixes the error where a mistyped role name would result in the user being added as a guest (fallback). It will now check if the `--role` flag is provided, and if so provides the value of this to the mutation, which if the user has typed incorrectly will result in a graphql error. The guest fallback remains for times where the `--role` flag is omitted.
closes #336
=> fix: pass role through to api directly to better capture misspelled roles

cmd/deploytarget.go, cmd/deploytargetconfig.go, cmd/environment.go, cmd/get.go, cmd/groups.go, cmd/list.go, cmd/login.go, cmd/notificationsemail.go, cmd/notificationsrocketchat.go, cmd/notificationsslack.go, cmd/notificationsteams.go, cmd/notificationswebhook.go, cmd/organization.go, cmd/project.go, cmd/raw.go, cmd/root.go, cmd/tasks.go, cmd/users.go, go.mod, go.sum
Allows for [versioned requests using machinery](https://github.com/uselagoon/machinery/pull/50) so that updates to schemas can be handled better.
Additionally, the lagoon api version check is performed whenever a token is refreshed, this gives the benefit of always being able to know the version of the api that is being targeted without the user having to specifically call the check. It can add a delay to token refreshes though, but will happen in the background like a normal token refresh anyway.
Eventually this could use the `.well-known/appspecific/sh.lagoon.discovery.json` endpoint when discovery is introduced properly, which would be faster than using the API version call.
=> refactor: add versioned requests for machinery based requests

cmd/notificationsemail.go, cmd/notificationsteams.go, cmd/notificationswebhook.go
Just fixes aliases for some notification commands
closes #340
=> fix: aliases for project notifications

cmd/root.go, cmd/shared.go, cmd/users.go, docs/commands/lagoon.md, docs/commands/lagoon_deploy_branch.md, docs/commands/lagoon_deploy_latest.md, docs/commands/lagoon_deploy_promote.md, docs/commands/lagoon_deploy_pullrequest.md, docs/commands/lagoon_reset-password.md, internal/mock/mock_importer.go, internal/mock/mock_me.go, pkg/lagoon/users/main.go, pkg/lagoon/users/users.go
* Added a `--reset-password` flag to send an email when adding a user
* Added a `reset-password` command to send an email for an existing user
n/a
=> Add password reset features

cmd/deploytarget.go, cmd/get.go, cmd/groups.go, cmd/list.go, cmd/organization.go, cmd/project.go, cmd/users.go, docs/commands/lagoon_add_project.md
Just refactors commands using `GetOrganizationByName` to check if the returned organization contains something, [since the API will return null](https://github.com/uselagoon/lagoon/blob/v2.19.0/services/api/src/resources/organization/resolvers.ts#L264) instead of an error
Also added an `organization-id` flag to the `add project` command to be able to shortcut `GetOrganizationByName` if the ID is known.
=> refactor: refactor and fix organizationbyname to error if organization not found

cmd/helpers.go, cmd/helpers_test.go, cmd/logs.go, cmd/root.go, pkg/lagoon/ssh/main.go
This PR adds support for this new log access feature in ssh-portal: https://github.com/uselagoon/lagoon-ssh-portal/pull/243
It allows you to access container logs from any Lagoon environment that you have permission to SSH to, via the command line.
The command can either collect existing logs, or "follow" live logs via `-f`.
Please do not merge this until https://github.com/uselagoon/lagoon-ssh-portal/pull/243 is merged, and lagoon-charts is updated to a version with this feature.
Feature - access logs from the CLI (#232)
Closes: #232
=> feat: add support for streaming container logs from services

cmd/deploy.go, cmd/deploytarget.go, cmd/environment.go, cmd/get.go, cmd/import.go, cmd/list.go, cmd/project.go, docs/commands/lagoon.md, docs/commands/lagoon_add_deploytarget.md, docs/commands/lagoon_add_project.md, docs/commands/lagoon_delete_deploytarget.md, docs/commands/lagoon_deploy_branch.md, docs/commands/lagoon_deploy_latest.md, docs/commands/lagoon_deploy_promote.md, docs/commands/lagoon_deploy_pullrequest.md, docs/commands/lagoon_list_deploytargets.md, docs/commands/lagoon_list_group-users.md, docs/commands/lagoon_logs.md, docs/commands/lagoon_update_deploytarget.md, docs/commands/lagoon_update_environment.md, docs/commands/lagoon_update_project.md
Just fixing up more flags. 
This also changes all the `openshift` flags and references to `deploytarget` and mentions kubernetes only too.
This is a breaking change, but in combination with all the other breaking changes that have been merged, we can call this out in the release notes that the release is considerably breaky
=> chore: update remaining flags, docs, and remove most openshift references

cmd/list.go, cmd/users.go, docs/commands/lagoon_delete_organization-administrator.md, docs/commands/lagoon_list.md, docs/commands/lagoon_list_organization-admins.md, go.mod, go.sum
This adds a new command to list just the organization administrators and their role, this is `list organization-admins`
It removes the `owner` column from the `list organization-users` query too, as this doesn't work properly.
=> feat: support for organization admins and changes to use role flag

cmd/get.go, cmd/list.go, docs/commands/lagoon_get_environment.md, docs/commands/lagoon_get_project.md, go.mod, go.sum
Updates the `list` and `get` environment and project commands to include the same information. Extends the `get` commands with a `--wide` flag that will extend the data with more fields if required.
```
$ lagoon list projects
ID	PROJECTNAME	GITURL                                      PRODUCTIONENVIRONMENT   PRODUCTIONROUTE         DEVENVIRONMENTS
1 	test       	git@github.com:shreddedbacon/d8-example.git main                	https://example.com     3/5
2 	test1       git@github.com:shreddedbacon/d8-example.git main                 	https://example2.com    0/5
3 	test2       git@github.com:shreddedbacon/d8-example.git main                 	https://example3.com    0/5
14	test3       git@github.com:shreddedbacon/d8-example.git	main                 	https://example4.com    0/5
15	test4 …
```
=> fix: list and get environment and project to display same data

cmd/config.go, cmd/deploy.go, cmd/deploytarget.go, cmd/deploytargetconfig.go, cmd/environment.go, cmd/get.go, cmd/groups.go, cmd/list.go, cmd/notificationsemail.go, cmd/notificationsrocketchat.go, cmd/notificationsslack.go, cmd/notificationsteams.go, cmd/notificationswebhook.go, cmd/organization.go, cmd/project.go, cmd/retrieve.go, cmd/tasks.go, cmd/users.go, cmd/variables.go, cmd/whoami.go, pkg/output/main.go, pkg/output/main_test.go
Changes the `render` functions in the `Output` package to return strings, allowing for the output to be captured in command testing (here https://github.com/uselagoon/lagoon-cli/pull/358). Updates all relevant commands to the use the modified `render` functions.
=> Change: Updates the output for Render functions

cmd/get.go, cmd/list.go, cmd/project.go, cmd/shared.go, cmd/users.go, docs/commands/lagoon_add_organization-administrator.md, docs/commands/lagoon_add_project.md, docs/commands/lagoon_list_deploytargets.md, docs/commands/lagoon_update_project.md, go.mod, go.sum
Converts some previously uint value flags (0/1) that represent booleans to be actual booleans, and fixes the way the values are added to the inputs of the mutations to prevent them being added by default and only added if they're defined specifically (either as true, or as a specific `--flag=false` value.
Additional fixes to the deploytarget list too to reduce how much data is returned, with new `--wide` and `--show-token` flag. These commands are only supported for `platform-owner`, just makes it easier to read the output.
Also adds the new `admin` role support from Lagoon v2.20.0 to organization owners commands, so that admins can be managed via the CLI now along with previous owner and viewer roles.
=> refactor: convert uint flags to boolean, other fixes and improvements

cmd/list.go, cmd/users.go, docs/commands/lagoon_list.md, docs/commands/lagoon_list_organization-admininstrators.md
Just a small fix to the `list organization-administrators` command to rename it from `list organization-admins` and updated the aliases of other commands
=> fix: rename list organization-administrator command to match others

cmd/root.go, cmd/users.go, cmd/variables.go
Just fixes some other missing new line output in some information output
=> fix: additional new lines on rendering info output

cmd/deploytargetconfig.go, cmd/environment.go, cmd/get.go, cmd/groups.go, cmd/list.go, cmd/notificationsemail.go, cmd/notificationsrocketchat.go, cmd/notificationsslack.go, cmd/notificationsteams.go, cmd/notificationswebhook.go, cmd/project.go, cmd/shared.go, cmd/users.go, cmd/variables.go
A number of commands don't have validation on key flags which results in errors & nil results. 
This adds additional validation & a helper func to better handle nil results. Also adds newlines where relevant due to the change in output in PR https://github.com/uselagoon/lagoon-cli/pull/364 
A couple examples:
Nil results
Error due to non-existent project being passed - `lagoon delete org-p -p invalidProject --organization-name lagoon-demo-organization` (More an api issue, but simple enough to handle here)
=> Fix: Adds better handling for nil results

cmd/environment.go, cmd/get.go, docs/commands/lagoon_update_environment.md
Converts environment `auto-idle` from `uint` to `bool` to reflect the refactor in https://github.com/uselagoon/lagoon-cli/pull/366.
=> Refactor: Refactors environment auto-idle from uint to boolean

.github/workflows/goreleaser.yaml, .github/workflows/lagoon-cli.yaml, .github/workflows/mkdocs.yaml
This PR updates the versions of outdated github actions, and the command used to generate goreleaser.
replaces #378
=> Goreleaser & GitHub Actions update

pkg/lagoon/ssh/main.go
Automated tests for DDev are failing because their CI does not instantiate an environment with a `known_hosts` file. Even when adding the `--strict-host-key-checking no` flag, the cli still fails.
This PR skips the filesystem check when strict host key checking is disabled.
https://github.com/ddev/ddev/pull/6524
=> fix: unable to skip strict host key checking when known_hosts file is missing

cmd/logs.go, cmd/ssh.go
Fixes a bug in the name lookup to determine which ssh portal to use when an environment name contains a `/`. 
The lookup will now check against the most common namespace name based on the project and environment name provided.
=> fix: check environment name or namespace combo for ssh usernames

cmd/get.go
Just a small fix to only check if the `privateKey` is returned if reveal is provided. Since the query is requesting `projectKey` on project now, anyone with access to a project can view this, but only certain roles can view the `privateKey`.
=> fix: return projectkey if reveal not provided

Dockerfile, cmd/config.go, cmd/helpers_test.go, cmd/list.go, cmd/login.go, cmd/logs.go, cmd/root.go, cmd/users.go, pkg/app/app.go, pkg/lagoon/ssh/main.go, pkg/output/main.go, pkg/output/main_test.go, pkg/updatecheck/updatecheck.go, pkg/updatecheck/updatecheck_test.go
Address go lint errors in #381
=> chore: address go linting

cmd/deploytargetconfig.go, cmd/environment.go, cmd/get.go, cmd/groups.go, cmd/list.go, cmd/project.go, cmd/tasks.go, go.mod, go.sum
Not all roles can use `GetMinimalProjectByName` due to the `openshift` lookup performed in that query. 
This uses changes in machinery to update the functions that used to require the project ID to now accept project name, this includes a minimal projectByName that just gets the project name and id now which will work for any role that has the permission to view the project. See https://github.com/uselagoon/machinery/pull/74 (now available in v0.0.30)
=> refactor: remove getminimalprojectbyname where possible

cmd/get.go, cmd/list.go, docs/commands/lagoon_get_deployment.md, docs/commands/lagoon_list_deployments.md
Update `get` and `list` deployments to include the `buildStep`. Move the fields `remoteId` and `created` fields into a new `--wide` flag to reduce the information displayed to only more relevant information.
Example of how this looks
```
$ lagoon list deployments -p example-project -e test
ID     	NAME               	STATUS  	BUILDSTEP                  	STARTED            	COMPLETED
234    	lagoon-build-j85815	complete	deployCompletedWithWarnings	2024-10-03 14:43:50	2024-10-03 14:47:05
233    	lagoon-build-q9h7a6	failed  	runningPostRolloutTasks    	2024-10-03 14:28:02	2024-10-03 14:31:48
232    	lagoon-build-lxec85	failed  	runningPostRolloutTasks    	2024-10-03 11:23:06	2024-10-03 11:30:20
$ lagoon list deployments -p example-project -e test --wide
ID     	NAME               	STATUS …
```
=> feat: include buildstep in deployment get, list

.github/dependabot.yaml, .github/dependency-review-config.yaml, .github/workflows/coverage.yaml, .github/workflows/dependency-review.yaml, .github/workflows/lint.yaml, .github/workflows/ossf-analysis.yaml, .github/workflows/release.yaml, .gitignore, README.md, pkg/app/app.go
Partially addresses #360.
Once this is merged, we can enable Dependabot at which point #360 can be closed.
=> Configure application security policy in CI

pkg/lagoon/ssh/main.go
Removes an errant space in the `service=%s` section of a command when attempting to ssh to a service.
=> fix: remove errant space in ssh command with service

cmd/login.go, docs/commands/lagoon.md, docs/commands/lagoon_login.md
This change forces the `lagoon login` command to refresh the token. Previously this command would only refresh a token if it was invalid, effectively doing nothing.
For users that use many keys, this can lead to problems where the token may be for another user that previously authenticated, but still had a valid token. With a user believing that `lagoon login` was clearing out the token.
This is addressed in #319, but that pull request has considerable changes that are breaking for users, so this pull request brings a version of that functionality to the current CLI format.
=> fix: force token refresh with lagoon login

Makefile, cmd/config.go, cmd/config_test.go, cmd/testdata/lagoon.yml, cmd/testdata/lagoon.yml.invalid, cmd/testdata/lagoon.yml.missing, cmd/update.go, cmd/variables.go, docs/commands/lagoon_add_variable.md, docs/config.md, docs/index.md, docs/troubleshooting.md, mkdocs.yml
The `configuration` docs were a bit out of date and referenced some amazeeio domains that shouldn't be used anymore. Eventually I'd like to remove the references to amazeeio, but that can be done in #319. This updates them with some newer output examples, and some changes to wording.
Fixed up a weird issue with the add and update variable commands so now the docs are correct.
Added a make target to serve the docs locally to edit docs and see changes easier. Big note, don't modify the `commands/*` files as they are still auto generated by `make docs`.
I also put together some basic troubleshooting information. Hopefully this will help some users resolve some problems themselves.
This has to merge after #409
=> docs: refresh documentation and add a troubleshooting page

cmd/variables.go, docs/commands/lagoon_update_variable.md
The 0.31.3 release introduced some refactoring of the add/update variable commands that inadvertently lead to flags not being attached to the variable update command. This PR reintroduces them.
=> fix: Adds missing flags to variable update

pkg/lagoon/ssh/main.go
With non-interactive ssh calls, the RunSSHCommand function was exiting with only an error returned, but not outputting anything that came back via stdout, as it would on successful calls.
This meant that we were losing some important information in the output. This PR simply ensures that if there _is_ data buffered from stdout, we're displaying in.
closes #426
=> fix: Always outputs stdout for running, non-interactive, shells

.github/workflows/lagoon-cli.yaml, Dockerfile
A multiarch build defines its own OS and ARCH - this PR ensures that the build is built as the correct architecture for the destination instead of falling back to linux/amd64
=> chore: allow builder to set OS/ARCH

cmd/logs.go, cmd/shared.go, cmd/ssh.go
Closes #457.
This PR introduces a new function `environmentCheck()` that checks a given environment name string belongs to a project, and if not, returns an error with valid options that the user has access to.
This PR only adds the check to the `ssh` command, but could be used for any command that mandates a project/environment input.
=> feat: improved error message for ssh on invalid environment name
