uselagoon/lagoon-cli

- Gopkg.lock
- Gopkg.toml
- app/app.go
- app/app_test.go
- app/fixtures/basic/.lagoon.yml
- app/fixtures/basic/docker-compose.yml
- cmd/project.go
- cmd/projectinfo.go
- cmd/root.go
> Lagoon detection

- README.md
Hi @mglaman - just checking this is ok with you as an acknowledgement - feel free to reword if you want, just want to make sure you get the credit!
(In addition - I intend to add you as the originator in the MIT licence we're about to add - that ok?)
> Add mglaman to acknowledgements section

- api/types.go
- cmd/add.go
- cmd/config.go
- cmd/delete.go
- cmd/deploy.go
- cmd/environment.go
- cmd/get.go
- cmd/list.go
- cmd/login.go
- cmd/notifications.go
- cmd/project.go
- cmd/root.go
- cmd/shared.go
- cmd/update.go
- cmd/variables.go
- go.mod
- graphql/main.go
- lagoon/environments/variables.go
- lagoon/projects/notifications.go
- lagoon/projects/variables.go
This PR aims to improve the flags that are configured for each command in the cli
> Improve Flags

- cmd/login.go
- cmd/root.go
This allows people to use encrypted ssh keys, or keys that are added to an ssh agent
Thanks @cdchris12 for doing the initial work on this.
> Add ability to use ssh-agent and encrypted ssh keys

- cmd/get.go
- docs/commands/lagoon_get_project-key.md
- lagoon/projects/main.go
When onboarding a project, being able to provide the public key for the project is a must. This allows the key to be collected easily.
Feature - Ability to extract the privatekey from a project and display the public key for use by deployment systems
> Get project keys

- cmd/web.go
closes #40 , fixes URL of web command
> #40 - fix formatting of UI URL

- cmd/run.go
- cmd/tasks.go
- docs/commands/lagoon_run_custom.md
- lagoon/environments/tasks.go
This PR allows custom tasks to be run against an environment. Usage is as follows
```
lagoon run custom -p example -e master -N "My Task" -S cli -c "ps -ef"
cat /path/to/my-script.sh | lagoon run custom -p example -e master -N "My Task" -S cli
lagoon run custom -p example -e master -N "My Task" -S cli -s /path/to/my-script.sh
```
Improvement - Allow custom tasks
closes #52
> Allow custom tasks

- cmd/ssh.go
- docs/commands/lagoon_ssh.md
- lagoon/ssh/main.go
Ability to run command via SSH
```
lagoon ssh -p example -e develop  -c php -s nginx -C env
```
Feature - Ability to run command via SSH
closes #53
> Ability to run command via SSH

- cmd/project.go
- graphql/main.go
- lagoon/users/main.go
- lagoon/users/users.go
Just some minor fixes for report card score
> minor fixes for report card

- cmd/project.go
- docs/commands/lagoon_add_project.md
- docs/commands/lagoon_update_project.md
Some options were initially hidden, these probably don't need to be hidden anymore
Change - Unhide options
closes #50
> Unhide hidden options

- cmd/root.go
API clients were getting created before the token was validated resulting in bad or no token being applied to graphql interactions. This resulted in errors when trying to run some commands initially.
Bugfix - API clients were created before generating the token if it was invalid
closes #63
> Token error on re-auth

- api/projects.go
When adding a project, not all flags were respected. This PR allows them all to be consumed if defined.
> Adding projects doesn't include all options

- cmd/list.go
- docs/commands/lagoon_list.md
- docs/commands/lagoon_list_group-projects.md
- docs/commands/lagoon_list_groups.md
- lagoon/users/groups.go
- lagoon/users/main.go
Being able to list groups and which projects are attached to a specific group
Feature - List groups, and projects in groups
none
> List groups, and projects within a group

- cmd/list.go
> fixing typo

- cmd/deploy.go
- docs/commands/lagoon_deploy_promote.md
- docs/commands/lagoon_list.md
- docs/commands/lagoon_list_environments.md
- lagoon/environments/main.go
Add the command to promote environments
```
lagoon deploy promote -p my-project -s my-source -d my-dest
```
Feature - Add promote command to deploy
none
> Add command to promote environments

- cmd/ssh.go
- lagoon/ssh/main.go
This adds better errors for SSH commands, rather than panic
Bugfix - Better errors for SSH commands
closes #75
> Better errors for SSH command

- cmd/groups.go
- cmd/login.go
- cmd/root.go
- pkg/app/app.go
- pkg/lagoon/environments/deployments.go
- pkg/lagoon/environments/tasks.go
- pkg/lagoon/projects/main_test.go
- pkg/lagoon/projects/notifications.go
- pkg/lagoon/users/users.go
- pkg/updatecheck/updatecheck.go
PR to fix ineffectual assignments
> Ineffectual assignment fixes

- cmd/login.go
This change adds some context to error handling in loginToken().
This is in support of the import/export PR.
Improvement - Add context to login token error handling
n/a
> Add some context to error handling in cmd.loginToken()

- pkg/graphql/main.go
This change simplifies the token verification logic.
This is in support of the import/export PR.
Improvement - Simplify token verification logic
n/a
> Simplify token verification logic

- cmd/project.go
- cmd/root.go
- docs/commands/lagoon_update_project.md
This allows project names to be changed using the `update project` command
It also solves a long running issue of automatically sorting commands alphabetically.
Change - Add flag to change project names
closes #96
> Add flag to update project to allow name change

- cmd/config.go
- docs/commands/lagoon_config_current.md
Just adds a way to display the current lagoon without any extra tools
```
lagoon config current
```
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
> Display current lagoon

- internal/schema/config.go
- pkg/api/types.go
New scopes were added to lagoon recently, should not impact backward compatability.
> Add new scopes

- cmd/config.go
- cmd/deploy.go
- cmd/environment.go
- cmd/groups.go
- cmd/notificationsrocketchat.go
- cmd/notificationsslack.go
- cmd/project.go
- cmd/users.go
- cmd/variables.go
Display more confirmation information when deleting resources from a Lagoon
Improvement - More verbose deletion confirmations
closes #99
> Additional confirmation for deletions

- cmd/variables.go
- docs/commands/lagoon_delete_variable.md
Documentation - updated the help text for the `lagoon variable delete` function.
> Updated help text for variable delete.

- internal/lagoon/export.go
Improvement - Sort exported EnvVariables by name (#114)
Closes #114
> Sort exported EnvVariables by name

- cmd/whoami.go
- internal/lagoon/me.go
This PR just does some minor refactoring of `whoami` command logic. This was my wind-down activity before bed last night..
Improvement - Minor refactoring of whoami command
n/a
> Minor refactoring on whoami command

- cmd/delete.go
Removes the alias for the delete command so it doesn't clash with deploy.
Bugfix - Removes the delete command alias (#121)
Closes #121
> Remove delete alias.

- pkg/lagoon/environments/main.go
- pkg/lagoon/environments/main_test.go
- pkg/lagoon/projects/main.go
- pkg/lagoon/projects/main_test.go
Improvement - Add OpenshiftProjectName to get and list commands for environments
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
> add OpenshiftProjectName to get and list of environments

- cmd/variables.go
This PR add the support for `CONTAINER_REGISTRY` and `INTERNAL_CONTAINER_REGISTRY` scopes to add variable command.
Improvement - CONTAINER_REGISTRY and INTERNAL_CONTAINER_REGISTRY scopes support (#150)
closes #150
> Added support for CONTAINER_REGISTRY and INTERNAL_CONTAINER_REGISTRY

- cmd/login.go
> Add note about using ssh-agent for encrypted private keys

- pkg/graphql/main.go
- pkg/lagoon/environments/variables.go
> Don't use project level envvars in the environment request

- cmd/config.go
- cmd/root.go
- docs/commands/lagoon_config_feature.md
Make the directory check opt-in and change the flag to `--enable-local-dir-check`
closes #127
> Make the local directory checking opt-in

- docs/config.md
> Pointing out the location of the .lagoon.yml file

- internal/schema/project.go
Exporting a project that is configured for active/standby doesn't export the `standbyProductionEnvironment` field, this PR adds support for that.
> Add standbyProductionEnvironment to export

- cmd/config.go
- cmd/root.go
Previously, if a user tried to use or set a context that doesn't exist, there is no error to let them know that it doesn't exist. 
closes #136
> Error if the chosen context doesn't exist

- cmd/list.go
- cmd/run.go
- cmd/tasks.go
- docs/commands/lagoon_list.md
- docs/commands/lagoon_list_invokable-tasks.md
- docs/commands/lagoon_run_invoke.md
- internal/schema/tasks.go
- pkg/api/types.go
- pkg/lagoon/environments/main.go
- pkg/lagoon/environments/tasks.go
This introduces basic functionality to list and invoke custom defined tasks
closes #193
> Feature - adding invokable tasks to cli (193)

- .github/workflows/lagoon-cli.yaml
- Dockerfile
- Makefile
- cmd/root.go
- docs/index.md
This PR fixes up the Dockerfile build and push workflow.
* It creates a valid semantic version for the dockerfile, based on the tag (if pushed) or previous tag+commit (if not a tag push)
```
tobybellwood@pop-os:~/sites/lagoon-cli$ docker run ghcr.io/uselagoon/lagoon-cli:dockerfile_fixup version
lagoon v0.11.6+4543157f (go1.14.15)
built 2021-09-16T04:27:36+0000
```
This also matches the `make build` logic
```
tobybellwood@pop-os:~/sites/lagoon-cli$ /home/tobybellwood/go/bin/lagoon --version
lagoon v0.11.6+4543157f (go version go1.17 linux/amd64)
built 2021-09-16T14:53:29+1000
```
It also creates an empty .lagoon.yml file in the docker image to avoid errors on start if run from the Dockerfile
```
tobybellwood@pop-os:~/sites/lagoon-cli$ docker run …
```
> fixup dockerfile creation and versioning

- pkg/graphql/main.go
- pkg/lagoon/environments/variables.go
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
> refactor: modify the way environment variables are retrieved for environments

- cmd/add.go
- cmd/environment.go
- cmd/list.go
- cmd/retrieve.go
- cmd/root.go
- docs/commands/lagoon.md
- docs/commands/lagoon_add.md
- docs/commands/lagoon_add_restore.md
- docs/commands/lagoon_get.md
- docs/commands/lagoon_get_backup.md
- docs/commands/lagoon_list.md
- docs/commands/lagoon_list_backups.md
- docs/commands/lagoon_retrieve.md
- docs/commands/lagoon_retrieve_backup.md
- internal/lagoon/client/_lgraphql/addRestore.graphql
- internal/lagoon/client/_lgraphql/backupsForEnvironmentByName.graphql
- internal/lagoon/client/lgraphql/lgraphql.go
- internal/lagoon/client/mutation.go
- internal/lagoon/client/query.go
- internal/lagoon/environments.go
- internal/mock/mock_importer.go
- internal/mock/mock_me.go
- internal/schema/backups.go
- internal/schema/environment.go
This adds support for interacting with backups, some example usage is as follows
```
$ lagoon list backups --project example-project --environment main
BACKUPID                                                        	SOURCE 	CREATED            	RESTORED	RESTORESTATUS 
eea8254c7500ba3de996aa8ad6af399183f04e17d4a8102fde539dbc93a90012	nginx  	2021-11-24 14:07:35	false   	-	
39b8dc3fc8b44765c8e6f1adee04c5b465e555ab791cc42d0d9e810d5b64297c	mariadb	2021-11-24 14:07:33	false   	-	
496ecdb854d49463f8655b210ddf17d3395d26b20a6f297b07cf99834c6336f0	nginx  	2021-11-23 14:07:36	false   	-	
45080860abd6d79b808dbd71836bf29e41918f1bf1f05f7ce732ada7674cc816	mariadb	2021-11-23 14:07:33	true    	successful	
77a60c200656e08ac5403f38b58657ecec155293323bd5313290399b75cf1c3d	nginx  	2021-11-22 14:07:35	false …
```
> feat: add support for listing, restoring, and getting backups for environments

- cmd/variables.go
To make sure the CLI is in line with what the API supports, we should allow empty values for environment variables.
closes #230
> feat: support empty values for adding environment variables

- docs/config.md
In a previous pull request (https://github.com/uselagoon/lagoon-cli/pull/243) I noted that the command for changing the default lagoon required the use of the --lagoon flag in order to succeed and this change was merged in. 
I have gone back to verify the rest of the documentation in this section and have identified that this same requirement exists for the other commands including:
* Adding a lagoon
* Deleting a lagoon
Attempting to execute the examples given in the documentation without the usage of the --lagoon flag will cause the operations to fail with:
```
Error: Missing arguments: Lagoon name is not defined
```
My change updates both the command documentation and the practical examples to demonstrate the required inclusion of this flag when interacting with the Lagoons using these …
> Corrections to lagoon interaction commands documentation

- cmd/deploytargetconfig.go
- docs/commands/lagoon_add_deploytarget.md
- docs/commands/lagoon_update_deploytarget.md
Just adding required fields for branches and pullrequests on adding deploytargetconfigs
Small documentation fix
> chore: minor fixes for deploytargetconfigs required fields and some docs

- cmd/project.go
- docs/commands/lagoon_update_project.md
- pkg/api/types.go
This adds the `deploymentsDisabled` flag to updating a project, this allows you to set the project to disable deploying environments. This is an administrator only flag, and is ignored if user is not an admin.
> feat: add flag to support disabling a project from being able to deploy

- cmd/project.go
- internal/mock/mock_importer.go
- internal/mock/mock_me.go
- pkg/api/types.go
This PR adds the ability to set the factsUi and problemsUi fields when updating a project
Users of lagoon-cli would like to be able to set these fields. This PR fixes that.
> Adds factsUi and ProblemsUi to update project command

- cmd/variables.go
When adding or updating a variable, check if the variable name is provided.
Fix - When adding or updating a variable, check if the variable name is provided.
> fix: error if name empty when adding or updating variables

- cmd/list.go
- docs/commands/lagoon_list_group-projects.md
Fixes the flag for list group-projects to require the name of the group to be provided
closes #134
> fix: flag description for list group-projects

- cmd/notificationsrocketchat.go
- cmd/notificationsslack.go
Fixes add slack and rocketchat to pass the channel value properly.
closes #278
> fix: add channel to slack and rocketchat notifications

- mkdocs.yml
Updated to include darkmode toggle to align with Lagoon docs.
> Included darkmode to align with Lagoon docs

- cmd/notificationsemail.go
- cmd/notificationsrocketchat.go
- cmd/notificationsslack.go
- cmd/notificationsteams.go
- cmd/notificationswebhook.go
- go.mod
- go.sum
Updated all `AddNotifications` commands to utilize `machinery`.
Requires: https://github.com/uselagoon/machinery/pull/32
> Improvement: Updated AddNotifications to utilize machinery

- .github/workflows/goreleaser.yaml
- .github/workflows/lagoon-cli.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- docs/commands/lagoon_add_notification_email.md
- docs/commands/lagoon_add_notification_microsoftteams.md
- docs/commands/lagoon_add_notification_rocketchat.md
- docs/commands/lagoon_add_notification_slack.md
- docs/commands/lagoon_add_notification_webhook.md
- go.mod
- go.sum
- pkg/api/main.go
- pkg/graphql/main.go
> chore: update to go 1.21

- go.mod
- go.sum
Just updating the crypto library used to a newer version
> chore: update golang/crypto

- go.mod
- go.sum
Revert service type change in machinery for unrelease v2.18.0 schema updates.
> revert: undo newer services changes

- go.mod
- go.sum
> Backport services

- .github/PULL_REQUEST_TEMPLATE.md
Just removing some unused change log information to reflect updates to pullrequest titles
> chore: adjust pullrequest template to remove unused changelog data

- go.mod
- go.sum
Just a quick fix to bump machinery to the latest version that contains some bug fixes
> chore: bump machinery version to latest

- .github/workflows/goreleaser.yaml
Just a small one to temporarily hardcode the goreleaser version until work can be done to update it properly
> chore: hardcode goreleaser version

- cmd/get.go
- cmd/list.go
Fixes an issue with a nil reference in get/list projects on `DevelopmentEnvironmentsLimit`
> fix: nil pointer check for get/list projects

- cmd/deploytargetconfig.go
Fix the check for pullrequests on updating deploytargetconfigs
> fix: pullrequest check on deploytargetconfig update

- cmd/deploy.go
Just fixes an incorrect flag check for branch-ref
> fix: branch-ref flag on deploy branch

- cmd/users.go
Updates the user add and delete SSH key functions to use the new API functions available in Lagoon to extend support for all key types.
> refactor: use newer sshkey functions to expand key support

- go.mod
- go.sum
Bug fix in machinery related to some changes introduced in #390
> chore: bump machinery version

- cmd/users.go
Just adds a comment when a user is created via the CLI
> chore: add comment to user addition command

- cmd/config.go
- cmd/root.go
- cmd/ssh.go
- cmd/users.go
- cmd/web.go
- pkg/lagoon/ssh/main.go
> chore: address more linting issues

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
Change the way the docker based build works. You may need to delete any `vendor` directories from the repository if they exist though.
closes #424
> build: change docker based building

- docs/config.md
Adds some notes about the two SSH key related flags for adding configurations.
> docs: add some information about the ssh key flags for config

- cmd/list.go
- docs/commands/lagoon_list.md
- docs/commands/lagoon_list_environment-services.md
Adds the ability to list the services that environment has deployed.
> feat: list environments services

- .github/tap-release.yml
- builds/release_template.md
- docs/index.md
Fixes some references to the brew `amazeeio` tap to be `uselagoon`
> fix(docs): use uselagoon tap name

- cmd/helpers.go
- cmd/list.go
- cmd/variables.go
- docs/commands/lagoon_add_variable.md
- docs/commands/lagoon_list.md
- docs/commands/lagoon_list_organization-variables.md
- docs/commands/lagoon_update_variable.md
* Added --organization-name to add/update variable
* Changes are backwards compatible with older lagoon API
* Added list organization-variables
Blocked  on https://github.com/uselagoon/machinery/pull/80.
> feat: add basic support for org env vars

- cmd/variables.go
- docs/commands/lagoon_add_variable.md
- docs/commands/lagoon_update_variable.md
Removes scope from command description & handles scope selection with a nil result and messaging.
Requires https://github.com/uselagoon/lagoon/pull/3973
> Change: Handles internal_container_registry scope deprecation
